[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python create_superuser.py && python manage.py collectstatic --noinput && gunicorn municipio_ia.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
healthcheckPath = ""
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10