# Generated by Django 5.1.2 on 2025-09-11 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(editable=False, max_length=20, unique=True)),
                ('peticionario_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('peticionario_id', models.CharField(blank=True, max_length=20, null=True)),
                ('peticionario_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('peticionario_correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('peticionario_direccion', models.TextField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(help_text='Archivo PDF del derecho de petición', upload_to='peticiones/')),
                ('transcripcion_completa', models.TextField(blank=True, help_text='Transcripción completa del documento extraída por IA')),
                ('estado', models.CharField(choices=[('sin_responder', 'Sin Responder'), ('respondido', 'Respondido')], default='sin_responder', max_length=20)),
                ('fuente', models.CharField(choices=[('gestion_documental', 'Gestión Documental'), ('correo_electronico', 'Correo Electrónico'), ('presencial', 'Presencial')], max_length=20)),
                ('fecha_radicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Derecho de Petición',
                'verbose_name_plural': 'Derechos de Petición',
                'ordering': ['-fecha_radicacion'],
            },
        ),
        migrations.CreateModel(
            name='ProcesamientoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('tiempo_procesamiento', models.FloatField(help_text='Tiempo en segundos')),
                ('modelo_ia_usado', models.CharField(default='gemini-pro', max_length=50)),
                ('estado_procesamiento', models.CharField(choices=[('exitoso', 'Exitoso'), ('error', 'Error'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('peticion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procesamiento_ia', to='peticiones.peticion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('funcionario_responsable', models.CharField(max_length=200)),
                ('archivo_respuesta', models.FileField(blank=True, null=True, upload_to='respuestas/')),
                ('peticion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='peticiones.peticion')),
            ],
            options={
                'ordering': ['-fecha_respuesta'],
            },
        ),
    ]
