# Generated by Django 5.1.2 on 2025-10-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde se ubica la dependencia (opcional)', max_length=100, null=True, verbose_name='Ciudad'),
        ),
    ]
