# Generated by Django 5.1.2 on 2025-09-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesamientoia',
            name='modelo_ia_usado',
            field=models.CharField(default='gemini-1.5-flash', max_length=50),
        ),
    ]
