# Generated by Django 5.1.2 on 2025-10-12 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0002_alter_dependencia_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoHabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del día no hábil', unique=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(help_text='Motivo del día no hábil (ej: Día de la Familia, Capacitación, etc.)', max_length=200, verbose_name='Descripción')),
                ('es_festivo_nacional', models.BooleanField(default=False, help_text='Marcar si es un festivo nacional de Colombia', verbose_name='Festivo Nacional')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Día No Hábil',
                'verbose_name_plural': 'Días No Hábiles',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='peticion',
            name='dependencia',
            field=models.ForeignKey(help_text='Dependencia encargada de responder la petición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peticiones', to='peticiones.dependencia', verbose_name='Dependencia Responsable'),
        ),
        migrations.AddField(
            model_name='peticion',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha máxima para responder (15 días hábiles)', null=True, verbose_name='Fecha de Vencimiento'),
        ),
    ]
