# Generated by Django 5.1.2 on 2025-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0002_alter_procesamientoia_modelo_ia_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='fecha_radicacion',
            field=models.DateTimeField(help_text='Fecha y hora de radicación del derecho de petición', verbose_name='Fecha de Radicación'),
        ),
    ]
